app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: 寻乐云
publisher_url: https://github.com/hiddify/hiddify-next
display_name: 寻乐云
executable_name: 寻乐云.exe
output_base_file_name: 寻乐云.exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\XunLeCloud"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - fa
  - ru
  - pt
  - tr
script_template: inno_setup.sas
